@host=https://localhost:7192

# Sign up request with form
POST {{host}}/api/auth/sign-up
Content-Type: application/x-www-form-urlencoded

&Username=JerryS
&Password=112233
&Name=Jerry
&Email=jerryseinfeld@mail.com