@host=https://localhost:7192

GET {{host}}/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDI2ZDJkNC00YmUzLTRlYmEtODMzZC1lNTY4N2I3NzNmMjciLCJuYW1laWQiOiJKZXJyeVMiLCJuYW1lIjoiSmVycnkiLCJqdGkiOiI0ODFiNmIzZC03MzJmLTQyMzItYmQyMS05ZGYyMDdhMmY2NzMiLCJleHAiOjE2NzA5NDgwMDMsImlzcyI6IkNvbW11bmlvbiIsImF1ZCI6IkNvbW11bmlvbiJ9.lgkLmnCVgIbsaolxREt2GPQKCgeq0YKwcpW8eyh9T2k