@host=https://localhost:7192
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJKZXJyeVNhIiwic3ViIjoiNDNkOTE5MDQtZGE2OS00YTQ2LTkxMjAtNjc2ZDNhN2Q0OTUxIiwibmFtZSI6IkplcnJ5IiwianRpIjoiMjU3NzZkZjQtNzcyNy00ZDQzLTk1MjItZmUzMGM5NmVkZWEwIiwiZXhwIjoxNjcxMTgxMDU4LCJpc3MiOiJDb21tdW5pb24iLCJhdWQiOiJDb21tdW5pb24ifQ.3c7GWVEpMlVRIdUWYFXDUG4dj5eEn91N70e55DbRqQc

# Create category request with form
POST {{host}}/api/admin/categories/rename-topic
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=---------------------------735323031399963166993862150

-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="CategoryId"

968c505e-8df4-47d2-bc67-5a96469b3cd6
-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="TopicId"

c26bad4c-d395-4242-9e43-fcc3f3b4df82
-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="NewTopicName"

Renamed Topic Name
-----------------------------735323031399963166993862150--
